version: '3.8'

services:
    qdrant:
        image: qdrant/qdrant:latest
        container_name: qdrant
        ports:
            - '6333:6333'
            - '6334:6334'
        volumes:
            - qdrant_storage:/qdrant/storage
        environment:
            - QDRANT__SERVICE__HTTP_PORT=6333
            - QDRANT__SERVICE__GRPC_PORT=6334
        restart: unless-stopped

    ollama:
        image: ollama/ollama:latest
        container_name: ollama
        ports:
            - '11434:11434'
        volumes:
            - ollama_data:/root/.ollama
        environment:
            - OLLAMA_HOST=0.0.0.0
        restart: unless-stopped

volumes:
    qdrant_storage:
    ollama_data:
